services:
  backstage:
    image: node:22-bookworm-slim
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "7007:7007"
    command: sh -c "npm install && npm dev"

